spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:financedb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:rakeshchandraswain2001@gmail.com}
    password: ${MAIL_PASSWORD:ozzc pwlp qalf yjxg}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    access-token-expiration: 7200000      # 2 hours in ms
    refresh-token-expiration: 604800000   # 7 days in ms

server:
  port: 8080

logging:
  level:
    com.financetracker: INFO
    org.springframework.security: WARN
    org.springframework.batch: WARN
